interfaces {
    {% for interface in interfaces %}
     {% if interface['if_name'] in ['ge-0/0/1','ge-0/0/2'] %}
       {{ interface['if_name']}} {
           unit 0 {
              family mpls;
           }
        }
     {% endif %}
    {% endfor %}
}

protocols {
    ldp {
      {% for interface in interfaces %}
       {% if interface['if_name'] in ['ge-0/0/1','ge-0/0/2','lo0'] %}
       interface {{ interface['if_name'] }}.0;
       {% endif %}
      {% endfor %}
    }
    mpls { 
    {% for interface in interfaces %}
      {% if interface['if_name'] in ['ge-0/0/1','ge-0/0/2'] %}
      interface {{ interface['if_name'] }}.0;
      {% endif %}
    {% endfor %}
    }
} 
