protocols {
	ospf {
	  {% for interface in interfaces %}
	   area {{ interface['area'] }} {
	     {% if interface['if_name'] != 'lo0' %}
	        interface {{ interface['if_name'] }};
	     {% else %}
	         interface {{ interface['if_name'] }} {
	          passive;
	         }

	     {% endif %}
	   }
      {% endfor %}
	}
}

security {
  zones {
  	security-zone trust {
  		host-inbound-traffic {
  			protocols{
  				all;
  			}
  		}
  		interfaces {
  		 {% for interface in interfaces %}
  		 {{ interface['if_name'] }} {
  		 	host-inbound-traffic {
  		 		system-services {
  		 			all;
  		 		}
  		 	}
  		 }
  		 {% endfor %}
  		}
  	}
  }
}
